### ISSUE TITLE
Ratchet guidance

### ISSUE THREAD

**Issue by chris-wood** [sframe-wg/sframe#157]
Should there be guidance on when to ratchet base keys instead of simply using the same base key with a new nonce? Right now, this is entirely up to the application, and for good reason. However, from the application's perspective, it may not be obvious when to choose between ratcheting and bumping the counter. A paranoid application might choose to ratchet for every SFrame encryption operation, which is a fine position to take if they're willing to deal with the rekey bandwidth/performance consequences. Maybe there's some text we can crib from other documents, e.g., maybe TLS or QUIC rekeying behavior?

**Comment by bifurcation** [comment]
This seems like an OK thing to document in security considerations.  I would probably bracket between two extremal examples: MLS ratchets on every send; TLS ratchets only on request, e.g., when you approach AEAD usage limits.

**Comment by bifurcation** [comment]
The two key-update operations available in the sender keys framework are (1) distribute a new key and (2) ratchet the current key.  (Corresponding to incrementing the key generation and ratchet step, respectively.)  All that happens in the KID.  The CTR must be incremented on each encryption so that all the nonces are unique.  I'm assuming that what you're asking about is advice between the two key update operations.
