### ISSUE TITLE
Using metadata before decryption

### ISSUE THREAD

**Issue by chris-wood** [sframe-wg/sframe#158]
The spec reads "A receiver SHOULD NOT use SFrame-authenticated metadata until after the SFrame decrypt function has authenticated it.” This really feels like a MUST NOT, as I can't imagine a scenario where attacker controlled data would be useful to applications. If it's going to stay as a SHOULD NOT, I think we should add some rationale.

**Comment by bifurcation** [comment]
This is a fair point.  On the one hand, MUST NOT is clearer.  On the other hand, I suspect there are cases where you want SFrame to authenticate some envelope information (e.g., RTP header data), but that envelope information is also used to route the packet to the right SFrame instance.  Such a use case is still safe, because if the envelope is false, decryption will fail and the packet will get dropped.  Maybe we frame as a MUST NOT with exception, something like "MUST NOT ... except MAY use to identify the proper SFrame context for decryption"
