### ISSUE TITLE
Spec is not clear about the metadata field

### ISSUE THREAD

**Issue by youennf** [sframe-wg/sframe#63]
The spec defines aad has header+metadata.
The metadata is expected to be generated by the encoder and then the metadata will be serialized in RTP header extensions.
The metadata is used to compute the authentication tag.

This makes it a requirement for metadata to be serialised to and deserialised from RTP header extensions without any loss of information. Otherwise, the receiver will not be able to validate the authentication tag.

Given the metadata should be redundant with the actual content, it is always possible for the receiver to validate the metadata  with the decrypted content.

That makes me wonder what we are trying to protect from by authenticating the metadata.
If useful, it would be good to give some advice on what metadata is expected to go there.

**Comment by murillo128** [comment]
I am not sure what is the metadata here, I would not make it e2ee authenticated. For example, the Dependency Descriptor is modified by the SFU to indicate which are the active layers (i.e. the ones being forwarded)

**Comment by youennf** [comment]
For RTP, I would think the metadata field would be empty as the data would probably go in RTP header extensions.
Maybe other transports have different requirements but I do not really like having metadata be sometimes in the SFrame payload and sometimes not in the SFrame payload depending on the underlying transport.

**Comment by bifurcation** [comment]
The current spec says that the metadata is provided by the application.  So the considerations you all are discussing seem like a problem for the application, not this document.  Can we close this issue?

**Comment by youennf** [comment]
Do we know usage of metadata in existing applications? If so, it would be good to document a bit more its expected use.
If no one is using it, should we remove it as a simplification?

**Comment by alvestrand** [comment]
RTP header extensions are (in general) expected to be changed by the SFU.

**Comment by martinthomson** [comment]
Richard asks us to consider if we need this.

@murillo128 asks for use cases for the data.  We should try to see if we can send everything protected, rather than just authenticated, but in the clear.

Jonathan would like to see an example of how an application might use this.  It would be annoying to have differences in how the data is interpreted.  Figure out of we really need it and take it out if not.

Richard says that use cases were for e2e for everything, but there was framing data that was necessary for the SFU.  This would prevent tampering.  It might be plausible that we might not find something concrete.

Rohan mentions that speaking indications for audio might not be protected, but they might be authenticated.  That seems like a classic example.

Harald's canonical example is the frame descriptor that describes the layering in SVC.  The SFU is expected to read that and throw away some frames.  It might modify the descriptor, to fit the next hop.  But there is value in copying the value that was used/modified before forwarding.  Metadata is instructions to the transmission system, but they need to be protected by other means.  What arrives might not be what is sent.  Stuff on the outside can be modified, legitimately.  Inside the packet, it will get to the other end.  These don't have to match up.  So we can simplify the model and split between outside and inside; this authentication-only option only confuses things.

Richard: for metadata to be useful, it needs to be unmodified.  Harald is saying that there is not much use for authenticated information.

Rohan: voice activity or energy levels are information that need to be viewed, but not modified.  That's an example.

Harald: RTP header extensions for client->SFU is different from the SFU->client, so that data is modified e2e anyway.

Bernard is confused by the term "metadata".  It covers a lot of things.  Dependency descriptor is already in the payload, but it is put outside to make it available to the SFU.  These are not used by the decoder.  It might be irrelevant to the SFU and maybe also to the receiver.

Richard was going to propose that we keep the authenticated metadata for now.  Explain what an application needs to do with this information (consistent view between sender/receiver).  Mark it at risk that needs more confirmation that it is useful/needed.  Revisit at WGLC.

Jonathan agrees about the conclusion.  Though cheap for SFrame is not necessarily cheap for applications, which might lead to us removing it.

**Comment by bifurcation** [comment]
@ghostofcookie and I reviewed the meeting recording and the above.  He is going to work up a PR that does the following:

* Clarify that the metadata is pure app-specified data (cf. #103)
* Add a note that the metadata is "at risk"
