### ISSUE TITLE
Provide clear guidance about replay

### ISSUE THREAD

**Issue by bifurcation** [sframe-wg/sframe#76]
The document is currently unclear on what replay checks are required.  We should decide what replay protections are required and describe them clearly.

For background, SRTP has [fairly stringent anti-replay protections](https://datatracker.ietf.org/doc/html/rfc3711#section-3.3.2), which accounts for a nontrivial amount of code in libsrtp.

The context for SFrame seems a bit different, since the outer transport will typically provide anti-replay support (SRTP and QUIC both do, for example).  So you're only worried about the SFU replaying frames.  But that still seems worth some level of defense.

Maybe a couple of simple bounds would do here?  Just tracking the highest CTR and rejecting frames with CTR older than a specific age would cover the worst abuse cases, like copy/pasting from different segments of the stream.  

That still wouldn't prevent the server from looping indefinitely over the replay window, say to show a receiver as silent when they were actually transmitting.  To address that, you would need a actual anti-replay, probably allowing some number >1 of legitimate replays.  So it seems like that either leads to SRTP-like full anti-replay (plus a bit), or to deciding that to leave this risk un-addressed.

**Comment by murillo128** [comment]
We would need to specify the CTR as an incremental counter (which I am in favor of). 

I think that a time based replay window vs a counter based one could solve the issue. I will try to work on an algorithm to solve this.

**Comment by murillo128** [comment]
>FWIW, I would probably be fine locking CTR to be a counter (as the name already suggests!). The only lingering doubt in my mind is whether you might want to support multiple senders under the same KID by segmenting the CTR space. But that's probably a bad idea, and KID should actually identify the sender.

+1

> I'm not sure what you mean by "time based" vs. "counter based"

Me neither.. yet 🤣

**Comment by bifurcation** [comment]
For context, SRTP says [the following](https://www.rfc-editor.org/rfc/rfc3711#section-3.3.2):

>   After the packet has been authenticated (if necessary the window is
>   first moved ahead), the replay list SHALL be updated with the new
>   index.
>
>   The Replay List can be efficiently implemented by using a bitmap to
>   represent which packets have been received, as described in the
>   Security Architecture for IP [[RFC2401](https://www.rfc-editor.org/rfc/rfc2401)].

Something at about the same level of granularity seems like it would be appropriate here.

**Comment by martinthomson** [comment]
Magnus W says that the question is about how much the underlying application can handle duplicates.  If the application can handle duplicates easily, then we have less need.

Richard: we could decide not to work on this issue.  Maybe we only care about reuse of a nonce-key pair.  As Magnus notes, we can flag this for the application to handle.

Martin: replay protections at multiple levels can leak information if they act differently at each layer.  It might be safer even not to have replay protection at all, though it changes the transport requirements

Jonathan wants e2e replay protection, so you might need that here, if you want to defend against a malicious SFU. That is where it might need to be SFrame proper.  It might not even be the same application in a true e2e context.  Say MOQ to RTP with SFrame over the top, so you can't say "the" application provides replay protection.

Harald remembers that we live in a packetized world where duplication happens.  Replay protection is completely useful for anything security-wise.

@murillo128 says we might want a time-based replay window.  We have to put something in the document about this.

Richard time rather than counter.

@murillo128 maybe one is easier to implement than the other.

@bifurcation maybe we can document both and let people choose.

Rohan replays by accident or malice differ based on the transport type.  Generic is complicated.  Saying we have got most of this with SRTP and provide some general guidance for cases with a malicious SFU or other examples.  You should build protections on a per-transport basis, not here.

Richard: in summary transports can't provide protection against replay by SFU, I might propose we note that there are trade-offs.  Protection against network attackers is provided by something else.  But receivers that are concerned about replay by intermediaries can apply a replay window based on time or counter.  That would be fairly loose and non-normative, so it would be advisory only.

Jonathan: What is your trust relationship with the SFU?  There are some things that you might trust it for.  Be specific about what.

**Comment by bifurcation** [comment]
@ghostofcookie and I reviewed the recording here, and he is going to work up a PR that adds a section to the Security considerations of the following form:

> ## Replay
> 
> * Replay by network attackers is assumed to be prevented by network-layer facilities (e.g., TLS, SRTP).  [[ This should reflected in "what the app has to do" section, cf #103 ]]
> * Senders MUST reject requests to encrypt multiple times with the same key and salt.  Since this leads to bad consequences [cite].
> * No mandatory anti-replay on the receiver side. Receivers MAY apply time- or counter-based anti-replay mitigations.
