### ISSUE TITLE
MUST statement for out-of-scope key management

### ISSUE THREAD

**Issue by youennf** [sframe-wg/sframe#97]
Feedback from https://mailarchive.ietf.org/arch/msg/sframe/e9-ZqTTrh_eL6vK2y7OovHt0740/

Section 7.2 states that key exchange is out of scope for this doc, yet it states that clients “MUST change their keys when new clients joins or leaves the call”. IMO if this is an absolute requirement of the RFC, as per the definition of an all caps MUST, then the exact requirements of this should be spelled out more, and possibly a reference protocol given.

**Comment by youennf** [comment]
The requirement being on the application level, I do not think MUST should be used here.

**Comment by youennf** [comment]
Lower-case `must`might be good enough.

**Comment by bifurcation** [comment]
I would propose a SHOULD could be appropriate, as a recommendation for the application-level key management.

**Comment by martinthomson** [comment]
We will have hard requirements for applications and some recommendations.  So maybe we can express an opinion on a recommendation, because it doesn't make sense to be a "MUST".

Jonathan question about use of 2119 language here, but these should be clearly requirements on applications that *use* SFrame.

Harald we need to document the security property that is provided, then you need to do X.  This is advice, not a 2119 requirement.

**Comment by alvestrand** [comment]
something like "If an application wants forward secrecy and post-compromise security, then the application has to change the keys every time someone joins and leaves the group".
