### ISSUE TITLE
section 5.1 is unclear about how to retrieve a key from its ID as it can be a new key or a ratchet of a new received key

### ISSUE THREAD

**Issue by youennf** [sframe-wg/sframe#99]
Feedback from https://mailarchive.ietf.org/arch/msg/sframe/e9-ZqTTrh_eL6vK2y7OovHt0740/

It might be worth adding more details to section 5.1 to more clearly spell out how sender keys should (or could) work. For example, it states that “A receiver who receives from a sender with a new KID computes the new key as above [using an HKDF ratchet]”, yet later on says that “Evicting a participant requires each sender to send a fresh sender key to all receivers.”. Given both of these, it is not clear how a sender would signal a receiver that a frame is using a “fresh sender key” as opposed to a ratchet (or multiple) of a previously received key.

**Comment by youennf** [comment]
This is really application territory here, maybe this section should spell out that this is exemplifying an overall good approach but is not the only one or a fully complete approach.
About ratchet or not, there could be different solutions (ratchet ==  odd kid, new key == even kid).

**Comment by bifurcation** [comment]
It seems like you could do a similar segmentation here to what is done in the MLS section, something like:

```
KID = (sender_id << (R + K)) + (key_generation << K) + (ratchet_step)
```

Where `sender_id` is constant for a meeting, `key_generation` increments by one every time a fresh sender key is sent, and `ratchet_step` increments every time you hash forward.

I wouldn't worry about being overly specific here, since Sections 5.1 and 5.2 are both optional, in the sense that an application could choose to use a totally different key management system.

**Comment by martinthomson** [comment]
See also #103.

No substantive feedback, but editors can work on a fix here.
